<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!--

        Licensed to the Apache Software Foundation (ASF) under one or more
        contributor license agreements.  See the NOTICE file distributed with
        this work for additional information regarding copyright ownership.
        The ASF licenses this file to You under the Apache License, Version 2.0
        (the "License"); you may not use this file except in compliance with
        the License.  You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    -->

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache.karaf.assemblies.features</groupId>
        <artifactId>features</artifactId>
        <version>4.2.15.fuse-7_11_1-00017</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>org.apache.karaf.features</groupId>
    <artifactId>base</artifactId>
    <name>Apache Karaf :: Assemblies :: Features :: Base</name>

    <properties>
        <appendedResourcesDirectory>${basedir}/../../../etc/appended-resources</appendedResourcesDirectory>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.karaf</groupId>
                <artifactId>karaf-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.soap</groupId>
            <artifactId>jakarta.xml.soap-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.jws</groupId>
            <artifactId>jakarta.jws-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.ws</groupId>
            <artifactId>jakarta.xml.ws-api</artifactId>
        </dependency>
        <dependency>
            <!-- can't upgrade to jakarta, see: https://github.com/eclipse-ee4j/jaf/issues/67 -->
            <groupId>com.sun.activation</groupId>
            <artifactId>javax.activation</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicemix.specs</groupId>
            <artifactId>org.apache.servicemix.specs.activation-api-1.2.1</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>txw2</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.istack</groupId>
            <artifactId>istack-commons-runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.specs</groupId>
            <artifactId>org.apache.karaf.specs.locator</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.specs</groupId>
            <artifactId>org.apache.karaf.specs.java.xml</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.specs</groupId>
            <artifactId>org.apache.karaf.specs.java.xml.ws</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.specs</groupId>
            <artifactId>org.apache.karaf.specs.activator</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf</groupId>
            <artifactId>org.apache.karaf.main</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf</groupId>
            <artifactId>org.apache.karaf.client</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.jaas</groupId>
            <artifactId>org.apache.karaf.jaas.boot</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.diagnostic</groupId>
            <artifactId>org.apache.karaf.diagnostic.boot</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.framework</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.external</groupId>
            <artifactId>opendmk_jmxremote_optional_jar</artifactId>
            <version>1.0-b01-ea</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.servicemix.specs</groupId>
            <artifactId>org.apache.servicemix.specs.activator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicemix.specs</groupId>
            <artifactId>org.apache.servicemix.specs.locator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.xerces</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.xalan</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.xalan-serializer</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
        </dependency>

        <dependency>
            <groupId>net.i2p.crypto</groupId>
            <artifactId>eddsa</artifactId>
        </dependency>

    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>${project.basedir}/src/main/resources</directory>
                <filtering>false</filtering>
                <includes>
                    <include>**/*</include>
                </includes>
            </resource>
            <resource>
                <directory>${project.basedir}/src/main/filtered-resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <useDefaultDelimiters>false</useDefaultDelimiters>
                    <delimiters>
                        <delimiter>@@</delimiter>
                    </delimiters>
                </configuration>
                <executions>
                    <execution>
                        <id>filter</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>resources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <!--
                                    This is effectively a different way to specify <library> elements in
                                    karaf-maven-plugin:assembly configuration, but without the ability
                                    to export/boot-delegate the packages
                                -->

                                <!-- special libraries to be available at very high classloader -->

                                <!-- this will be endorsed in JDK8 and -\-patch-module=java.xml in JDK11 -->
                                <artifactItem>
                                    <groupId>org.apache.karaf.specs</groupId>
                                    <artifactId>org.apache.karaf.specs.java.xml</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <!-- this will be endorsed in JDK8 and part of boot classloader in JDK11 -->
                                <artifactItem>
                                    <groupId>org.apache.karaf.specs</groupId>
                                    <artifactId>org.apache.karaf.specs.java.xml.ws</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <!-- this has to be endorsed as well in JD8, because it's used by the two above -->
                                <artifactItem>
                                    <groupId>org.apache.karaf.specs</groupId>
                                    <artifactId>org.apache.karaf.specs.locator</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <!--
                                    To have compatibility between JDK8 and JDK11, annotation-api will also go to
                                    endorsed dir for JDK8 and boot classloader of JDK11 (configured in bin/karaf)
                                -->
                                <artifactItem>
                                    <groupId>jakarta.annotation</groupId>
                                    <artifactId>jakarta.annotation-api</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.google.code.findbugs</groupId>
                                    <artifactId>jsr305</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.servicemix.bundles</groupId>
                                    <artifactId>org.apache.servicemix.bundles.xerces</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.servicemix.bundles</groupId>
                                    <artifactId>org.apache.servicemix.bundles.xalan</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.servicemix.bundles</groupId>
                                    <artifactId>org.apache.servicemix.bundles.xalan-serializer</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.servicemix.specs</groupId>
                                    <artifactId>org.apache.servicemix.specs.activation-api-1.2.1</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>javax.validation</groupId>
                                    <artifactId>validation-api</artifactId>
                                    <outputDirectory>target/classes/resources/lib/endorsed</outputDirectory>
                                </artifactItem>

                                <!--
                                    These libraries are used in place of (some) java.se.ee modules removed in JDK 11:
                                     - Annotations (mind that javax.annotation.processing package comes from java.compiler module)
                                       which is stored in endorsed/ directory for JDK8
                                     - JAXB API
                                     - Activation API + Implementation
                                     - SAAJ API
                                     - JAXB Implementation (for Karaf feature parsing)
                                     - JWS API (javax.jws, javax.jws.soap)
                                     - JAX-WS API
                                    These will be exported by system bundle and bootdelegated to ensure there's
                                    only one source of JAXB/JAX-WS/Activation/Annotation/SAAJ packages
                                -->
                                <artifactItem>
                                    <groupId>jakarta.xml.bind</groupId>
                                    <artifactId>jakarta.xml.bind-api</artifactId>
                                    <outputDirectory>target/classes/resources/lib/jdk9plus</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>jakarta.xml.soap</groupId>
                                    <artifactId>jakarta.xml.soap-api</artifactId>
                                    <outputDirectory>target/classes/resources/lib/jdk9plus</outputDirectory>
                                </artifactItem>
                                <!-- JAXB implementation is required for Karaf feature parsing -->
                                <artifactItem>
                                    <groupId>org.glassfish.jaxb</groupId>
                                    <artifactId>jaxb-runtime</artifactId>
                                    <outputDirectory>target/classes/resources/lib/jdk9plus</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.jaxb</groupId>
                                    <artifactId>txw2</artifactId>
                                    <outputDirectory>target/classes/resources/lib/jdk9plus</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.sun.istack</groupId>
                                    <artifactId>istack-commons-runtime</artifactId>
                                    <outputDirectory>target/classes/resources/lib/jdk9plus</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>jakarta.jws</groupId>
                                    <artifactId>jakarta.jws-api</artifactId>
                                    <outputDirectory>target/classes/resources/lib/jdk9plus</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>jakarta.xml.ws</groupId>
                                    <artifactId>jakarta.xml.ws-api</artifactId>
                                    <outputDirectory>target/classes/resources/lib/jdk9plus</outputDirectory>
                                </artifactItem>

                                <!-- Remaining fundamental libraries -->
                                <artifactItem>
                                    <groupId>org.apache.karaf</groupId>
                                    <artifactId>org.apache.karaf.main</artifactId>
                                    <outputDirectory>target/classes/resources/lib/boot</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.osgi</groupId>
                                    <artifactId>osgi.core</artifactId>
                                    <outputDirectory>target/classes/resources/lib/boot</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.karaf.specs</groupId>
                                    <artifactId>org.apache.karaf.specs.activator</artifactId>
                                    <outputDirectory>target/classes/resources/lib/boot</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.glassfish.external</groupId>
                                    <artifactId>opendmk_jmxremote_optional_jar</artifactId>
                                    <outputDirectory>target/classes/resources/lib/boot</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>net.i2p.crypto</groupId>
                                    <artifactId>eddsa</artifactId>
                                    <outputDirectory>target/classes/resources/lib/boot</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.servicemix.specs</groupId>
                                    <artifactId>org.apache.servicemix.specs.activator</artifactId>
                                    <outputDirectory>target/classes/resources/lib/boot</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.servicemix.specs</groupId>
                                    <artifactId>org.apache.servicemix.specs.locator</artifactId>
                                    <outputDirectory>target/classes/resources/lib/boot</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.karaf</groupId>
                                    <artifactId>org.apache.karaf.client</artifactId>
                                    <outputDirectory>target/classes/resources/system/org/apache/karaf/org.apache.karaf.client/${project.version}</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.felix</groupId>
                                    <artifactId>org.apache.felix.framework</artifactId>
                                    <outputDirectory>target/classes/resources/system/org/apache/felix/org.apache.felix.framework/${felix.framework.version}</outputDirectory>
                                    <destFileName>org.apache.felix.framework-${felix.framework.version}.jar
                                    </destFileName>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.eclipse.platform</groupId>
                                    <artifactId>org.eclipse.osgi</artifactId>
                                    <outputDirectory>target/classes/resources/system/org/eclipse/platform/org.eclipse.osgi/${equinox.version}</outputDirectory>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.sun.winsw</groupId>
                                    <artifactId>winsw</artifactId>
                                    <version>${winsw.version}</version>
                                    <classifier>net4</classifier>
                                    <type>exe</type>
                                    <outputDirectory>target/classes/resources/bin/contrib</outputDirectory>
                                    <destFileName>karaf-service-win.exe</destFileName>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>jenkins</id>
            <name>jenkins</name>
            <url>https://repo.jenkins-ci.org/releases/</url>
        </repository>
    </repositories>
</project>
